# Generated by Django 4.2 on 2026-07-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
